# Generated by Django 3.1.1 on 2020-09-27 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlbutcher', '0007_auto_20200926_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugClickCounter',
            fields=[
                ('slug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='urlbutcher.url')),
                ('click_counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SlugClick',
        ),
    ]
