# Generated by Django 3.1.1 on 2020-09-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlbutcher', '0008_auto_20200927_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlugClickCounter',
        ),
    ]
