# Generated by Django 3.1.1 on 2020-09-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlbutcher', '0009_delete_slugclickcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugClickCounter',
            fields=[
                ('slug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='urlbutcher.url')),
                ('click_counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
